[tool.black]
line-length = 88
target-version = ["py313"]   # change to your actual Python version

[tool.isort]
profile = "black"
line_length = 88
combine_as_imports = true
force_sort_within_sections = true
skip = [".venv", "build", "dist", "old_builds", "patches"]

[tool.mypy]
python_version = "3.13"
warn_unused_configs = true
warn_return_any = true
warn_unused_ignores = true
disallow_untyped_defs = true
disallow_incomplete_defs = true
check_untyped_defs = true
no_implicit_optional = true
show_error_codes = true
ignore_missing_imports = true

[tool.pytest.ini_options]
minversion = "7.0"
addopts = "-ra -q"
testpaths = [
    "backend/tests",
]



